name: seasons
description: "Flutter-based application for voting at PFUR University"
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

# ------------------ APP DEPENDENCIES ------------------
dependencies:
  flutter:
    sdk: flutter

  # For iOS style icons
  cupertino_icons: ^1.0.8

  # State Management (BLoC)
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # UI & Styling
  google_fonts: ^6.2.1
  intl: ^0.20.2
  # Secure Storage
  flutter_secure_storage: ^9.2.2

  # Firebase (If used)
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

  # Local Notifications
  flutter_local_notifications: ^18.0.1

  flutter_svg: ^2.2.2
  http: ^1.5.0
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  bloc: ^9.2.0

# ----------------- DEV DEPENDENCIES -----------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  # For generating app launcher icons
  flutter_launcher_icons: ^0.14.4

  # Recommended lints for good coding practices
  flutter_lints: ^6.0.0

  bloc_test: ^10.0.0
  mocktail: ^1.0.3

# ----------------- FLUTTER CONFIG -----------------
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/backgrounds/

  fonts:
    - family: HemiHead
      fonts:
        - asset: assets/fonts/Hemi Head Bd It.otf

# ------------- LAUNCHER ICON CONFIG -------------
flutter_launcher_icons:
  image_path: "icon.png"
  ios: true
  android: true
  remove_alpha_ios: true
  min_sdk_android: 24
